---
## This playbook deploys the whole application stack in this site.  

# Apply common configuration to all hosts
- hosts: all
  roles:
  - common

# Configure and deploy database servers.
- hosts: dbservers:tag_ansible_group_dbservers
  user: root
  roles:
  - db

# Configure and deploy the web servers. Note that we include two roles here, 
# the 'base-apache' role which simply sets up Apache, and 'web' which includes
# our example web application.
- hosts: webservers:tag_ansible_group_webservers
  user: root

  roles:
  - base-apache
  - web

# Configure and deploy the load balancer(s).
- hosts: lbservers:tag_ansible_group_lbservers
  user: root
  roles:
  - haproxy

# Configure and deploy the Nagios monitoring node(s).
- hosts: monitoring:tag_ansible_group_monitoring
  user: root
  roles:
  - base-apache
  - nagios
