---
# This Playbook runs all the common plays in the deployment 

- name: Create the hosts file for all machines
  template: src=../roles/common/templates/hosts.j2 dest=/etc/hosts

- name: Creates the repository for 10Gen  
  template: src=../roles/common/templates/10gen.repo.j2 dest=/etc/yum.repos.d/10gen.repo

- name: Download the EPEL repository RPM
  get_url: url=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm dest=/tmp/ force=yes

- name: Install EPEL RPM
  yum: name=/tmp/epel-release-6-8.noarch.rpm state=installed

- name: Clean up
  command: rm -f /tmp/epel-release-6-8.noarch.rpm

- name: Install the mongodb package
  yum: name=$item state=installed
  with_items:
   - mongo-10gen
   - mongo-10gen-server
   - bc
   - python-pip

- name: Install the latest pymongo package
  pip: name=pymongo state=latest use_mirrors=no 

- name: Create the iptables file
  template: src=../roles/common/templates/iptables.j2 dest=/etc/sysconfig/iptables
  notify: restart iptables 

