---
# This playbook will install nagios

- name: install nagios 
  yum: pkg=$item state=installed
  with_items:
   - nagios
   - nagios-plugins
   - nagios-plugins-nrpe
   - nagios-plugins-ping
   - nagios-plugins-ssh
   - nagios-plugins-http
   - nagios-plugins-mysql
   - nagios-devel
  notify: restart httpd

- name: create nagios config dir
  file: path=/etc/nagios/ansible-managed state=directory
  tags:
   - nagios-setup

- name: configure nagios
  copy: src=nagios.cfg dest=/etc/nagios/nagios.cfg
  tags:
   - nagios-setup
  notify: restart nagios

- name: configure localhost monitoring
  copy: src=localhost.cfg dest=/etc/nagios/objects/localhost.cfg
  tags:
   - nagios-setup
  notify: restart nagios

- name: create the nagios object files
  template: src=servers.cfg.j2
            dest=/etc/nagios/ansible-managed/servers.cfg
  tags:
   - nagios-setup
  notify: restart nagios

- name: start nagios
  service: name=nagios state=started enabled=yes
