---
## This playbook deploys the whole application stack in this site.  

# Configure and deploy database servers.
- hosts: tag_ansible_group_windows_dbservers
  connection: winrm

  vars:
    ansible_ssh_port : 5986

  roles:
  - mssql

  tags: 
  - db

# Configure and deploy the web servers. Note that we include two roles here, 
# the 'base-apache' role which simply sets up Apache, and 'web' which includes
# our example web application.
- hosts: tag_ansible_group_windows_webservers
  connection: winrm

  vars:
    ansible_ssh_port : 5986


  roles:
  - iis 
  - web

  tags: 
  - web

# Configure and deploy the load balancer(s).
- hosts: tag_ansible_group_windows_lbservers

  vars:
    ansible_ssh_private_key_file: /var/lib/awx/.ssh/id_rsa

  roles:
  - common 
  - haproxy
  
  tags: 
  - lb

