- hosts: all
  connection: local
  gather_facts: no
  tasks:
   - fail: msg=" Please make sure the variables  id is specified and unique in the command line -e id=uniquedev1"
     when: id is not defined
   - name: Create Instance
     ec2: >
      region="{{ region }}"
      zone="{{ zone }}"
      id="{{ id }}"
      ec2_access_key="{{ ec2_access_key }}"
      ec2_secret_key="{{ ec2_secret_key }}"
      keypair="{{ keypair }}"
      instance_type="{{ instance_type }}"
      image="{{ image }}"
      wait=true
      group="{{ group }}"
      instance_tags='{"type": "openshift_servers", "id":"{{ id }}"}'
      count="{{ count }}"
     register: ec2

   - name: Delete Instance
     ec2:
      state: 'absent'
      instance_ids: "{{ item }}"
     with_items:  ec2.instance_ids
